### ISSUE TITLE
NoC router images

### ISSUE THREAD

**Issue by bniazmand** [Project-Bonfire/Bonfire#1]
![header_flit](https://user-images.githubusercontent.com/7483294/32893854-a6231db8-cae3-11e7-8e1b-bab16d3f02d2.png)
![body_1_flit](https://user-images.githubusercontent.com/7483294/32893855-a64db212-cae3-11e7-8d61-7c109c617da6.png)
![other_body_flit](https://user-images.githubusercontent.com/7483294/32893856-a66679b4-cae3-11e7-96f6-999235638bc3.png)
![tail_flit](https://user-images.githubusercontent.com/7483294/32893857-a67ec384-cae3-11e7-8223-4c6d22bfee8f.png)

![credit_based_router_2](https://user-images.githubusercontent.com/7483294/31229560-d6368154-a9e9-11e7-94aa-25878fade972.png)

![ni](https://cloud.githubusercontent.com/assets/7483294/24898084/3a2cd0f4-1ea4-11e7-8e89-ffd7ae797eeb.png)

<img width="586" alt="screen shot 2017-01-23 at 13 02 22" src="https://cloud.githubusercontent.com/assets/6337603/22201424/3f3c954a-e16c-11e6-9ef9-e3fe965dde45.png">

![routers_big_picture](https://cloud.githubusercontent.com/assets/6337603/21461254/96301d12-c958-11e6-8860-efe689082bd7.png)

[Routers_big_picture.pdf](https://github.com/Project-Bonfire/Bonfire/files/654886/Routers_big_picture.pdf)

![untitled drawing](https://cloud.githubusercontent.com/assets/6337603/20792150/0dc06bf8-b7c9-11e6-90bf-643e3ee0f0b4.png)

<img width="1195" alt="screen shot 2016-04-21 at 10 16 38 pm" src="https://cloud.githubusercontent.com/assets/7483294/14721466/29629d3c-080f-11e6-82b5-402e5311a1b6.png">

<img width="1235" alt="router_credit_based_fc" src="https://cloud.githubusercontent.com/assets/7483294/19738609/c29aa504-9bc0-11e6-8caf-ce54b9bedf02.png">

![allocator](https://cloud.githubusercontent.com/assets/7483294/21403995/cd651ac2-c7c7-11e6-953b-0c28da0c821e.png)

![fifo_one_hot_credit_based_fc](https://cloud.githubusercontent.com/assets/7483294/19738905/b4fd847e-9bc1-11e6-8654-2c3d33885485.png)

<img width="1154" alt="fifo_one_hot_packet_drop" src="https://cloud.githubusercontent.com/assets/7483294/19838526/f32c9c42-9ed9-11e6-8bb7-c63a777ca979.png">

![copy of schedule and depend system 1](https://cloud.githubusercontent.com/assets/6337603/22199785/0e3ed856-e165-11e6-85e0-b18df339932b.png)

![noc_lv_network](https://cloud.githubusercontent.com/assets/7483294/20517394/8c58ec4c-b0a3-11e6-9d54-d2c57beb2344.png)

<img width="704" alt="router_big_picture" src="https://cloud.githubusercontent.com/assets/7483294/21228462/88e93ad0-c2e6-11e6-861f-8c6256bd0a16.png">

**Comment by AlexDaniel** [comment]
Moved to https://github.com/Project-Bonfire/Bonfire/wiki/Images.
