### ISSUE TITLE
Software requirements (iteration limit?)

### ISSUE THREAD

**Issue by AlexDaniel** [Project-Bonfire/Bonfire#26]
I tried running the simulation locally but I bump into iteration limit:
```
# ** Error: (vsim-3601) Iteration limit reached at time 0 ns.
```
I increased ``IterationLimit`` in ``modelsim.ini`` but this didn't help. That's on 64-bit version of modelsim (10.2c). The simulation works fine on lab computers, so apparently there's something wrong with my setup. Tried looking for a solution but no luck so far.

Is it a known issue? I think additional instructions (or requirements), if any, should be listed in [user-manual](https://github.com/Project-Bonfire/Bonfire/wiki/user-manual). That said, it is possible that there is some issue with the design itself…

That's on master HEAD without any modifications (in fact I even cloned it separately to be 100% sure…).

**Comment by siavooshpayandehazad** [comment]
turn off optimization and increase test-bench clock to 10ns.

**Comment by AlexDaniel** [comment]
By the way, it seems to be working with optimizations also. I guess you will not be able to see the signals nicely this way, but it works.

**Comment by AlexDaniel** [comment]
Hm, or what was the fix to actually make the signals appear in the wave viewer?

**Comment by AlexDaniel** [comment]
Ah, this is now resolved.
