### ISSUE TITLE
Checker images

### ISSUE THREAD

**Issue by bniazmand** [Project-Bonfire/Bonfire#3]
![lbdr 3](https://cloud.githubusercontent.com/assets/6337603/16546124/c18fcecc-4149-11e6-9c78-e3a4d9dd29de.png)

![lbdr high level 1](https://cloud.githubusercontent.com/assets/6337603/16547312/06915ebe-4172-11e6-952a-6d6d78f5d377.png)

![fifo_low_level](https://cloud.githubusercontent.com/assets/6337603/16552864/04644ace-41cd-11e6-9d5d-7686f9546d6b.png)

![picture3](https://cloud.githubusercontent.com/assets/7483294/15372276/6f40c39e-1d48-11e6-93c2-1e7e81785101.png)

![fifo_control_part_checkers](https://cloud.githubusercontent.com/assets/7483294/15654931/8fa0da94-2698-11e6-9d8d-aa852a06b038.png)

![picture2](https://cloud.githubusercontent.com/assets/7483294/15372731/88637f4a-1d4a-11e6-90a0-a54d6ef6e946.png)

**Comment by AlexDaniel** [comment]
Moved to https://github.com/Project-Bonfire/Bonfire/wiki/Images
